import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const hasSession = await cookies(); // セッションがあるか確認
  // console.log("Cookies from Next.js:", Object.fromEntries(hasSession)); // ここでデバッグ
  // const sessionCookie = hasSession.get("laravel_session");


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header>
          {sessionCookie && (
            <div>
              <div>
                <h1>Session Cookie</h1>
                <pre>{JSON.stringify(sessionCookie, null, 2)}</pre>
              </div>
              <form action={logout}>
                <button
                  type="submit"
                  className="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600"
                >
                  ログアウト
                </button>
              </form>
            </div>
          )}
        </header> */}
        {children}
      </body>
    </html>
  );
}
